services:
  - type: web
    name: property-management
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: FLASK_ENV
        value: production 